service: token-api
provider:
  name: aws
  stage: prod
  runtime: nodejs14.x
  region: us-east-1
  memorySize: 128
functions:
  app:
    handler: index.handler
    environment:
        INFURA_KEY: ${env:INFURA_KEY}
    events: 
      - http: 
          path: /cmk/circulating_supply_raw
          method: ANY
          cors: true
      - http: 
          path: /crucible/wizard_island_avg_apy
          method: ANY
          cors: true